name: powwow
version: git
version-script: git -C /build/powwow/parts/powwow/src describe --tags --always --long
summary: Powwow is a client program intended mainly for playing MUDs
description: |
  powwow is a client program, which replaces telnet for the lazy mudder who wants some (only some?) extra features. It is primarily designed for DikuMUDs, but nothing prevents its use for other types of muds. powwow is based on another client, cancan, and cancan was originally inspired by tintin (yet another client) by Peter Unold (pjunold@daimi.aau.dk), but is entirely re-written. powwow also implements the MUME remote editing protocol, which enables you to edit texts on the mud using your own favourite editor, several texts at once if you have a windowing terminal.

grade: stable
confinement: strict
base: core18

apps:
  powwow:
    command: locales-launch powwow
    desktop: share/applications/powwow.desktop
    plugs:
      - home
      - network
  movieplay:
    command: locales-launch powwow-movieplay
    plugs:
      - home
  movie2ascii:
    command: locales-launch powwow-movie2ascii
    plugs:
      - home
  muc:
    command: locales-launch powwow-muc
    plugs:
      - home

parts:
  powwow:
    plugin: autotools
    source: https://github.com/MUME/powwow
    source-type: git
    source-branch: master
    build-packages:
      - pkg-config
      - libncurses5-dev
    stage-packages:
      - libncurses5

  locales-launch:
    plugin: nil
    stage-snaps:
      - locales-launch
    stage-packages:
      # For localedef(1)
      - libc-bin
      # For locale data used by localedef(1)
      - locales

  desktop-integration:
    plugin: copy
    source: .
    files:
      powwow.desktop: usr/share/applications/powwow.desktop
    snap:
      - usr/share
    after: [powwow]
